repo_url: https://github.com/Requisitos-de-Software/2023.2-Economia-DF
repo_name: 2023.2-Economia-DF

site_name: Economia DF
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01-31.08.2023.md
    - Reunião 2: atas/Reuniao02-05.09.2023.md
    - Reunião 3: atas/Reuniao03-13.09.2023.md
    - Reunião 4: atas/Reuniao04-15.09.2023.md
    - Reunião 5: atas/Reuniao05-20.09.2023.md
    - Reunião 6: atas/Reuniao06-22.09.2023.md
    - Reunião 7: atas/Reuniao07-04.10.2023.md
    - Reunião 8: atas/Reuniao08-06.10.2023.md
    - Reunião 9: atas/Reuniao09-11.10.2023.md
    - Reunião 10: atas/Reuniao10-13.10.2023.md
    - Reunião 11: atas/Reuniao11-18.10.2023.md
    - Reunião 12: atas/Reuniao12-24.10.2023.md
    - Reunião 13: atas/Reuniao13-01.11.2023.md
    - Reunião 14: atas/Reuniao14-10.11.2023.md
    - Reunião 15: atas/Reuniao15-15.11.2023.md
  - Apresentação:
    - Apresentação 1: apresentacoes/Apresentação 1 - 15.09.2023.md
    - Apresentação 2: apresentacoes/Apresentação 2 - 29.09.2023.md
    - Apresentação 3: apresentacoes/Apresentação 3 - 24.10.2023.md
    - Apresentação 4: apresentacoes/Apresentação 4 - 07.11.2023.md
    - Apresentação 5.1: apresentacoes/Apresentação 5.1 - 14.11.2023.md
    - Apresentação 6: apresentacoes/Apresentação 6 - 20.11.2023.md
  - Planejamento do projeto:
    - Heatmap de disponibilidade: planejamento do projeto/heatmap-disponibilidade.md
    - Ferramentas do projeto: planejamento do projeto/ferramentas.md
    - Aplicativos avaliados: planejamento do projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento do projeto/app-selecionado.md
    - Rich Picture: planejamento do projeto/rich-picture.md
    - Cronograma planejado: planejamento do projeto/cronograma_planejado.md
    - Cronograma executado: planejamento do projeto/cronograma_executado.md 
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - Grupo de Foco: elicitacao/tecnicas-perfil-usuario/grupo_de_foco.md
      - Questionário: elicitacao/tecnicas-perfil-usuario/questionario.md
      - Perfil de Usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Elicitação de Requisitos:
      - Brainstorming: elicitacao/tecnicas-elicitacao/brainstorming.md
      - Instrospecção: elicitacao/tecnicas-elicitacao/instrospeccao.md
      - Observação: elicitacao/tecnicas-elicitacao/observação.md
    - Requisitos Elicitados: elicitacao/requisitos-elicitados.md
    - Priorização de Requisitos:
      - Requisitos Priorizados: elicitacao/requisitos_priorizados.md
      - First Things First: elicitacao/tecnicas-priorizacao/first-thing-first.md
      - In or Out: elicitacao/tecnicas-priorizacao/in our out.md
      - 100$: elicitacao/tecnicas-priorizacao/100$.md
  - Modelagem de Requisitos:
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/casos-de-uso.md
    - Validação dos Casos de Uso: modelagem/validacao-casos-de-uso.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
    - Léxicos: modelagem/lexicos.md
  - Ágil:
    - Backlog: modelagem/agil/backlog.md
    - Histórias de Usuário: modelagem/agil/historia-de-usuario.md
    - NFR Framework: modelagem/agil/nfr-framework.md
  - Verificação:
    - Grupo 2:
      - Panorama geral: verificacao/Grupo-02/verificacao-panorama-geral.md
      - Entrega 1:
        - Planejamento da verificação: verificacao/Grupo-02/Entrega-01/planejamento-verificacao-e1-grupo2.md
        - Ferramentas: verificacao/Grupo-02/Entrega-01/ferramentas.md
        - Cronograma: verificacao/Grupo-02/Entrega-01/cronograma.md
        - Aplicativos: verificacao/Grupo-02/Entrega-01/aplicativos.md
        - Heatmap de disponibilidade: verificacao/Grupo-02/Entrega-01/heatmap.md
        - Rich Picture: verificacao/Grupo-02/Entrega-01/rich_picture.md
      - Entrega 2:
        - Planejamento da verificação: verificacao/Grupo-02/Entrega-02/planejamento-verificacao.md
        - Perfil do usuário:
          - Questionário: verificacao/Grupo-02/Entrega-02/questionario.md
        - Personas: verificacao/Grupo-02/Entrega-02/personas.md
        - Elicitação de requisitos: 
          - Storyboard: verificacao/Grupo-02/Entrega-02/storyboard.md
          - Glossário: verificacao/Grupo-02/Entrega-02/glossario.md
          - Entrevista: verificacao/Grupo-02/Entrega-02/entrevista.md
          - Instrospecção: verificacao/Grupo-02/Entrega-02/introspecçao.md
          - Requisitos elicitados: verificacao/Grupo-02/Entrega-02/requisitos-elicitados.md
        - Priorização:
          - $100: verificacao/Grupo-02/Entrega-02/priorizacao/100$.md
          - First Things First: verificacao/Grupo-02/Entrega-02/priorizacao/first_things_first.md
          - Three Level Scale: verificacao/Grupo-02/Entrega-02/priorizacao/three_level_scale.md
      - Entrega 3:
        - Planejamento da verificação: verificacao/Grupo-02/Entrega-03/planejamento-verificacao-e3-grupo2.md
        - Casos de uso: verificacao/Grupo-02/Entrega-03/casos-de-uso.md
        - Especificação suplementar: verificacao/Grupo-02/Entrega-03/especificacao-suplementar.md
        - Cenários: verificacao/Grupo-02/Entrega-03/cenarios.md
        - Léxicos: verificacao/Grupo-02/Entrega-03/lexicos.md
      - Entrega 4:
        - Planejamento da verificação: verificacao/Grupo-02/Entrega-04/planejamento-verificacao-e4-grupo2.md
        - NFR Framework: verificacao/Grupo-02/Entrega-04/nfr_framework.md
        - Product backlog: verificacao/Grupo-02/Entrega-04/product-backlog.md
        - Histórias de usuário: verificacao/Grupo-02/Entrega-04/historias-do-usuario.md
    - Grupo 1:
      - Entrega 1:
        - Planejamento da verificação: verificacao/Grupo-01/Entrega-01/planejamento-verificacao-e1-grupo1.md
        - Ferramentas: verificacao/Grupo-01/Entrega-01/ferramentas.md
        - Cronograma planejado: verificacao/Grupo-01/Entrega-01/cronograma_planejado.md
        - Cronograma executado: verificacao/Grupo-01/Entrega-01/cronograma_executado.md
        - Aplicativos Avaliados: verificacao/Grupo-01/Entrega-01/app_avaliados.md
        - Aplicativo Selecionado: verificacao/Grupo-01/Entrega-01/app_escolhido.md
        - Heatmap de disponibilidade: verificacao/Grupo-01/Entrega-01/heatmap.md
        - Rich Picture: verificacao/Grupo-01/Entrega-01/rich_picture.md
      - Entrega 2:
        - Planejamento da verificação: verificacao/Grupo-01/Entrega-02/planejamento-verificacao-e2-grupo1.md
        - 100$: verificacao/Grupo-01/Entrega-02/100$.md
        - Brainstorming: verificacao/Grupo-01/Entrega-02/brainstorming.md
        - First Things First: verificacao/Grupo-01/Entrega-02/first-thing-first.md
        - Grupo de foco: verificacao/Grupo-01/Entrega-02/Grupo-de-foco.md
        - In or Out: verificacao/Grupo-01/Entrega-02/in-our-out.md
        - Instrospecção: verificacao/Grupo-01/Entrega-02/instrospecção.md
        - Observação: verificacao/Grupo-01/Entrega-02/observacao.md
        - Perfil do Usuário: verificacao/Grupo-01/Entrega-02/perfil-de-usuario.md
        - Personas: verificacao/Grupo-01/Entrega-02/personas.md
        - Questionário: verificacao/Grupo-01/Entrega-02/questionario.md
        - Requisitos Elicitados: verificacao/Grupo-01/Entrega-02/requisitos-elicitados.md
        - Requisitos Priorizados: verificacao/Grupo-01/Entrega-02/requisitos-priorizados.md
      - Entrega 3:
        - Planejamento da verificação: verificacao/Grupo-01/Entrega-03/planejamento-verificacao-e3-grupo1.md
        - Casos de uso: verificacao/Grupo-01/Entrega-03/casos-de-uso.md
        - Validação dos Casos de Uso: verificacao/Grupo-01/Entrega-03/validacao-uc.md
        - Especificação suplementar: verificacao/Grupo-01/Entrega-03/especificacao-suplementar.md
        - Cenários: verificacao/Grupo-01/Entrega-03/cenarios.md
        - Léxicos: verificacao/Grupo-01/Entrega-03/lexicos.md
      - Entrega 4:
        - Planejamento da verificação: verificacao/Grupo-01/Entrega-04/planejamento-verificacao-e4-grupo1.md
        - NFR Framework: verificacao/Grupo-01/Entrega-04/nfr_framework.md
        - Backlog: verificacao/Grupo-01/Entrega-04/backlog.md
        - Histórias de usuário: verificacao/Grupo-01/Entrega-04/historia_de_usuario.md
      - Entrega 6:
        - Planejamento da verificação: verificacao/Grupo-01/Entrega-06/planejamento-verificacao-e6-grupo1.md
        - Backward From: verificacao/Grupo-01/Entrega-06/backward-fromc.md
        - Foward From: verificacao/Grupo-01/Entrega-06/forward-fromc.md
        - Matriz de Rastreabilidade: verificacao/Grupo-01/Entrega-06/matriz-de-rastreabilidade.md
  - Rastreabilidade:
    - Backward From: rastreabilidade/backward_from.md
    - Foward From: rastreabilidade/forward_from.md
    - Matriz de Rastreabilidade: rastreabilidade/matriz_de_rastreabilidade.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: green
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: green
      accent: lime
  favicon: imagens/logo-economida-df.png
  logo: imagens/logo-economida-df.png


  language: pt-BR
  extra_css: [stylesheets/extra.css]