repo_url: https://github.com/Requisitos-de-Software/2023.2-Economia-DF
repo_name: 2023.2-Economia-DF

site_name: Economia DF
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reunião 1 - 31.08.2023.md
    - Reunião 2: atas/Reunião 2 - 05.09.2023.md
    - Reunião 3: atas/Reunião 3 - 13.09.2023.md
    - Reunião 4: atas/Reunião 4 - 15.09.2023.md
    - Reunião 5: atas/Reunião 5 - 20.09.2023.md
    - Reunião 6: atas/Reunião 6 - 22.09.2023.md
  - Apresentação:
    - Apresentação 1: apresentacoes/Apresentação 1 - 15.09.2023.md
  - Planejamento do projeto:
    - Heatmap de disponibilidade: planejamento do projeto/heatmap-disponibilidade.md
    - Ferramentas do projeto: planejamento do projeto/ferramentas.md
    - Aplicativos avaliados: planejamento do projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento do projeto/app-selecionado.md
    - Rich Picture: planejamento do projeto/rich-picture.md
    - Cronograma planejado: planejamento do projeto/cronograma_planejado.md
    - Cronograma executado: planejamento do projeto/cronograma_executado.md 
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - Grupo de Foco: elicitacao/tecnicas-perfil-usuario/grupo_de_foco.md
      - Questionário: elicitacao/tecnicas-perfil-usuario/questionario.md
      - Perfil de Usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Elicitação de Requisitos:
      - Brainstorming: elicitacao/tecnicas-elicitacao/brainstorming.md
      - Instrospecção: elicitacao/tecnicas-elicitacao/instrospeccao.md
      - Observação: elicitacao/tecnicas-elicitacao/observação.md
    - Requisitos Elicitados: elicitacao/requisitos-elicitados.md
    - Priorização de Requisitos:
      - Requisitos Priorizados: elicitacao/requisitos_priorizados.md
      - First Things First: elicitacao/tecnicas-priorizacao/first-thing-first.md
      - In or Out: elicitacao/tecnicas-priorizacao/in our out.md
      - 100$: elicitacao/tecnicas-priorizacao/100$.md
    


  
    


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: green
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: green
      accent: lime


  language: pt-BR
  extra_css: [stylesheets/extra.css]