repo_url: https://github.com/Requisitos-de-Software/2023.2-Economia-DF
repo_name: 2023.2-Economia-DF

site_name: Economia DF
nav:
  - Home: index.md
  - Atas:
    - Reunião 1: atas/Reuniao01-31.08.2023.md
    - Reunião 2: atas/Reuniao02-05.09.2023.md
    - Reunião 3: atas/Reuniao03-13.09.2023.md
    - Reunião 4: atas/Reuniao04-15.09.2023.md
    - Reunião 5: atas/Reuniao05-20.09.2023.md
    - Reunião 6: atas/Reuniao06-22.09.2023.md
    - Reunião 7: atas/Reuniao07-04.10.2023.md
    - Reunião 8: atas/Reuniao08-06.10.2023.md
    - Reunião 9: atas/Reuniao09-11.10.2023.md
    - Reunião 10: atas/Reuniao10-13.10.2023.md
    - Reunião 11: atas/Reuniao11-18.10.2023.md
    - Reunião 12: atas/Reuniao12-24.10.2023.md
  - Apresentação:
    - Apresentação 1: apresentacoes/Apresentação 1 - 15.09.2023.md
    - Apresentação 2: apresentacoes/Apresentação 2 - 29.09.2023.md
    - Apresentação 3: apresentacoes/Apresentação 3 - 24.10.2023.md
    - Apresentação 4: apresentacoes/Apresentação 4 - 07.11.2023.md
  - Planejamento do projeto:
    - Heatmap de disponibilidade: planejamento do projeto/heatmap-disponibilidade.md
    - Ferramentas do projeto: planejamento do projeto/ferramentas.md
    - Aplicativos avaliados: planejamento do projeto/lista-apps-avaliados.md
    - Aplicativo selecionado: planejamento do projeto/app-selecionado.md
    - Rich Picture: planejamento do projeto/rich-picture.md
    - Cronograma planejado: planejamento do projeto/cronograma_planejado.md
    - Cronograma executado: planejamento do projeto/cronograma_executado.md 
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - Grupo de Foco: elicitacao/tecnicas-perfil-usuario/grupo_de_foco.md
      - Questionário: elicitacao/tecnicas-perfil-usuario/questionario.md
      - Perfil de Usuário: elicitacao/perfil_usuario.md
    - Personas: elicitacao/personas.md
    - Elicitação de Requisitos:
      - Brainstorming: elicitacao/tecnicas-elicitacao/brainstorming.md
      - Instrospecção: elicitacao/tecnicas-elicitacao/instrospeccao.md
      - Observação: elicitacao/tecnicas-elicitacao/observação.md
    - Requisitos Elicitados: elicitacao/requisitos-elicitados.md
    - Priorização de Requisitos:
      - Requisitos Priorizados: elicitacao/requisitos_priorizados.md
      - First Things First: elicitacao/tecnicas-priorizacao/first-thing-first.md
      - In or Out: elicitacao/tecnicas-priorizacao/in our out.md
      - 100$: elicitacao/tecnicas-priorizacao/100$.md
  - Modelagem de Requisitos:
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/casos-de-uso.md
    - Validação dos Casos de Uso: modelagem/validacao-casos-de-uso.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
    - Léxicos: modelagem/lexicos.md
  - Ágil:
    - Backlog: modelagem/agil/backlog.md
    - Histórias de Usuário: modelagem/agil/historia-de-usuario.md
    - NFR Framework: modelagem/agil/nfr-framework.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: green
      accent: purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: green
      accent: lime


  language: pt-BR
  extra_css: [stylesheets/extra.css]